language: julia
codecov: true
os:
    - linux
julia:
    - 1.2

notifications:
    email: false
sudo: false

after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
